#!/usr/bin/env python3
"""Embed frontend assets into a Windows .rc file and loader source."""

from __future__ import annotations

import argparse
import os
import sys

RESOURCE_BASE_ID = 2000
RESOURCE_TYPE = "KUTIE_ASSET"


def collect_assets(frontend_dir: str) -> list[tuple[str, str]]:
    assets: list[tuple[str, str]] = []
    for root, _, files in os.walk(frontend_dir):
        for name in sorted(files):
            full_path = os.path.join(root, name)
            rel_path = os.path.relpath(full_path, frontend_dir).replace("\\", "/")
            assets.append((rel_path, full_path))
    assets.sort(key=lambda item: item[0].lower())
    return assets


def safe_symbol(path: str) -> str:
    symbol = path.replace("/", "_").replace(".", "_").replace("-", "_").upper()
    return f"KUTIE_ASSET_{symbol}"


def write_outputs(frontend_dir: str, output_dir: str) -> int:
    assets = collect_assets(frontend_dir)
    os.makedirs(output_dir, exist_ok=True)

    ids_header = os.path.join(output_dir, "asset_ids.h")
    rc_path = os.path.join(output_dir, "assets.rc")
    loader_path = os.path.join(output_dir, "asset_loader.cpp")

    with open(ids_header, "w", encoding="utf-8") as header:
        header.write("// Generated by tools/embed_assets.py\n#pragma once\n\n")
        for index, (virtual_path, _) in enumerate(assets):
            header.write(f"#define {safe_symbol(virtual_path)} {RESOURCE_BASE_ID + index}\n")
        header.write(f"\n#define KUTIE_ASSET_COUNT {len(assets)}\n")

    with open(rc_path, "w", encoding="utf-8") as rc:
        rc.write("// Generated by tools/embed_assets.py\n")
        rc.write('#include "asset_ids.h"\n\n')
        for virtual_path, disk_path in assets:
            rc.write(f'{safe_symbol(virtual_path)} {RESOURCE_TYPE} "{disk_path.replace(chr(92), "/")}"\n')

    with open(loader_path, "w", encoding="utf-8") as loader:
        loader.write("// Generated by tools/embed_assets.py\n")
        loader.write('#include "kutie/asset_bundle.hpp"\n')
        loader.write('#include "asset_ids.h"\n')
        loader.write("#include <Windows.h>\n")
        loader.write("#include <vector>\n\n")
        loader.write("namespace kutie {\n\n")
        loader.write("void AssetBundle::LoadEmbedded(void* module_handle) {\n")
        loader.write("    HMODULE module = static_cast<HMODULE>(module_handle);\n")
        loader.write("    if (!module) {\n")
        loader.write("        return;\n")
        loader.write("    }\n\n")

        for virtual_path, _ in assets:
            symbol = safe_symbol(virtual_path)
            loader.write("    {\n")
            loader.write(f'        HRSRC resource = FindResourceW(module, MAKEINTRESOURCEW({symbol}), L"{RESOURCE_TYPE}");\n')
            loader.write("        if (resource) {\n")
            loader.write("            HGLOBAL global = LoadResource(module, resource);\n")
            loader.write("            if (global) {\n")
            loader.write("                const DWORD size = SizeofResource(module, resource);\n")
            loader.write("                const void* data = LockResource(global);\n")
            loader.write("                if (data && size > 0) {\n")
            loader.write("                    std::vector<std::uint8_t> bytes(\n")
            loader.write("                        static_cast<const std::uint8_t*>(data),\n")
            loader.write("                        static_cast<const std::uint8_t*>(data) + size);\n")
            loader.write(f'                    Put("/{virtual_path}", std::move(bytes));\n')
            loader.write("                }\n")
            loader.write("            }\n")
            loader.write("        }\n")
            loader.write("    }\n")

        loader.write("}\n\n")
        loader.write("} // namespace kutie\n")

    print(f"Embedded {len(assets)} assets from {frontend_dir}")
    return len(assets)


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed Kutie frontend assets")
    parser.add_argument("frontend_dir", help="Directory containing frontend files")
    parser.add_argument("-o", "--output", required=True, help="Output directory for generated files")
    args = parser.parse_args()

    if not os.path.isdir(args.frontend_dir):
        print(f"Frontend directory not found: {args.frontend_dir}", file=sys.stderr)
        return 1

    write_outputs(args.frontend_dir, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
